// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.synonyms');
goog.require('Blockly.Msg');

Blockly.Msg["PROCEDURES_DEFRETURN_TITLE"] = "PROCEDURES_DEFNORETURN_TITLE";
Blockly.Msg["CONTROLS_IF_IF_TITLE_IF"] = "CONTROLS_IF_MSG_IF";
Blockly.Msg["CONTROLS_WHILEUNTIL_INPUT_DO"] = "CONTROLS_REPEAT_INPUT_DO";
Blockly.Msg["CONTROLS_IF_MSG_THEN"] = "CONTROLS_REPEAT_INPUT_DO";
Blockly.Msg["LISTS_GET_SUBLIST_INPUT_IN_LIST"] = "LISTS_INLIST";
Blockly.Msg["CONTROLS_IF_ELSE_TITLE_ELSE"] = "CONTROLS_IF_MSG_ELSE";
Blockly.Msg["PROCEDURES_DEFRETURN_PROCEDURE"] = "PROCEDURES_DEFNORETURN_PROCEDURE";
Blockly.Msg["TEXT_CREATE_JOIN_ITEM_TITLE_ITEM"] = "VARIABLES_DEFAULT_NAME";
Blockly.Msg["LISTS_GET_INDEX_INPUT_IN_LIST"] = "LISTS_INLIST";
Blockly.Msg["PROCEDURES_DEFRETURN_COMMENT"] = "PROCEDURES_DEFNORETURN_COMMENT";
Blockly.Msg["CONTROLS_IF_ELSEIF_TITLE_ELSEIF"] = "CONTROLS_IF_MSG_ELSEIF";
Blockly.Msg["PROCEDURES_DEFRETURN_DO"] = "PROCEDURES_DEFNORETURN_DO";
Blockly.Msg["CONTROLS_FOR_INPUT_DO"] = "CONTROLS_REPEAT_INPUT_DO";
Blockly.Msg["LISTS_GET_INDEX_HELPURL"] = "LISTS_INDEX_OF_HELPURL";
Blockly.Msg["LISTS_INDEX_OF_INPUT_IN_LIST"] = "LISTS_INLIST";
Blockly.Msg["CONTROLS_FOREACH_INPUT_DO"] = "CONTROLS_REPEAT_INPUT_DO";
Blockly.Msg["LISTS_CREATE_WITH_ITEM_TITLE"] = "VARIABLES_DEFAULT_NAME";
Blockly.Msg["TEXT_APPEND_VARIABLE"] = "VARIABLES_DEFAULT_NAME";
Blockly.Msg["MATH_CHANGE_TITLE_ITEM"] = "VARIABLES_DEFAULT_NAME";
Blockly.Msg["LISTS_SET_INDEX_INPUT_IN_LIST"] = "LISTS_INLIST";
