name: Lint commit messages
on: [pull_request]

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.sha }}"

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: wagoid/commitlint-github-action@4973fb2da492818040d483817dd647c73b67eb52 # v5
