name: Copilot review
on:
  pull_request_target:
    types: [labeled]

jobs:
  copilot-review:
    if: github.event.label.name == 'copilot-review'
    permissions:
      pull-requests: write
    uses: scratchfoundation/.github/.github/workflows/copilot-review.yml@main
