name: Copilot review
on:
  pull_request_target:
    types: [labeled]

jobs:
  copilot-review:
    if: github.event.label.name == 'copilot-review'
    permissions:
      pull-requests: write
    uses: scratchfoundation/.github/.github/workflows/copilot-review.yml@5d4bb0bc18fc3f20a2e2bcb274b3920cf7fa24f4 # main
    secrets:
      COPILOT_REVIEW_TOKEN: ${{ secrets.COPILOT_REVIEW_TOKEN }}
